// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.29.0

package com.google.protobuf;

/**
 * <pre>
 * Wrapper message for `bytes`.
 *
 * The JSON representation for `BytesValue` is JSON string.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.BytesValue}
 */
public final class BytesValue extends
    GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.BytesValue)
        BytesValueOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    RuntimeVersion.validateProtobufGencodeVersion(
      RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      BytesValue.class.getName());
  }
  // Use BytesValue.newBuilder() to construct.
  private BytesValue(GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BytesValue() {
    value_ = ByteString.EMPTY;
  }

  public static final Descriptors.Descriptor
      getDescriptor() {
    return WrappersProto.internal_static_google_protobuf_BytesValue_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return WrappersProto.internal_static_google_protobuf_BytesValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.BytesValue.class, com.google.protobuf.BytesValue.Builder.class);
  }

  public static final int VALUE_FIELD_NUMBER = 1;
  private ByteString value_ = ByteString.EMPTY;
  /**
   * <pre>
   * The bytes value.
   * </pre>
   *
   * <code>bytes value = 1;</code>
   * @return The value.
   */
  @Override
  public ByteString getValue() {
    return value_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!value_.isEmpty()) {
      output.writeBytes(1, value_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!value_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, value_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.BytesValue)) {
      return super.equals(obj);
    }
    com.google.protobuf.BytesValue other = (com.google.protobuf.BytesValue) obj;

    if (!getValue()
        .equals(other.getValue())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.BytesValue parseFrom(
      java.nio.ByteBuffer data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      java.nio.ByteBuffer data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      ByteString data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      ByteString data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.BytesValue parseFrom(byte[] data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      byte[] data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.BytesValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.BytesValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.BytesValue parseDelimitedFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      CodedInputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.BytesValue parseFrom(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.BytesValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Wrapper message for `bytes`.
   *
   * The JSON representation for `BytesValue` is JSON string.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.BytesValue}
   */
  public static final class Builder extends
      GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.BytesValue)
      BytesValueOrBuilder {
    public static final Descriptors.Descriptor
        getDescriptor() {
      return WrappersProto.internal_static_google_protobuf_BytesValue_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WrappersProto.internal_static_google_protobuf_BytesValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.BytesValue.class, com.google.protobuf.BytesValue.Builder.class);
    }

    // Construct using com.google.protobuf.BytesValue.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      value_ = ByteString.EMPTY;
      return this;
    }

    @Override
    public Descriptors.Descriptor
        getDescriptorForType() {
      return WrappersProto.internal_static_google_protobuf_BytesValue_descriptor;
    }

    @Override
    public com.google.protobuf.BytesValue getDefaultInstanceForType() {
      return com.google.protobuf.BytesValue.getDefaultInstance();
    }

    @Override
    public com.google.protobuf.BytesValue build() {
      com.google.protobuf.BytesValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.google.protobuf.BytesValue buildPartial() {
      com.google.protobuf.BytesValue result = new com.google.protobuf.BytesValue(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.protobuf.BytesValue result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.value_ = value_;
      }
    }

    @Override
    public Builder mergeFrom(Message other) {
      if (other instanceof com.google.protobuf.BytesValue) {
        return mergeFrom((com.google.protobuf.BytesValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.BytesValue other) {
      if (other == com.google.protobuf.BytesValue.getDefaultInstance()) return this;
      if (other.getValue() != ByteString.EMPTY) {
        setValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              value_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ByteString value_ = ByteString.EMPTY;
    /**
     * <pre>
     * The bytes value.
     * </pre>
     *
     * <code>bytes value = 1;</code>
     * @return The value.
     */
    @Override
    public ByteString getValue() {
      return value_;
    }
    /**
     * <pre>
     * The bytes value.
     * </pre>
     *
     * <code>bytes value = 1;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      value_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The bytes value.
     * </pre>
     *
     * <code>bytes value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.BytesValue)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.BytesValue)
  private static final com.google.protobuf.BytesValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.BytesValue();
  }

  public static com.google.protobuf.BytesValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.BytesValue of(ByteString value) {
    return newBuilder().setValue(value).build();
  }

  private static final Parser<BytesValue>
      PARSER = new AbstractParser<BytesValue>() {
    @Override
    public BytesValue parsePartialFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static Parser<BytesValue> parser() {
    return PARSER;
  }

  @Override
  public Parser<BytesValue> getParserForType() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.BytesValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

