// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/wrappers.proto
// Protobuf Java Version: 4.29.0

package com.google.protobuf;

/**
 * <pre>
 * Wrapper message for `int32`.
 *
 * The JSON representation for `Int32Value` is JSON number.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Int32Value}
 */
public final class Int32Value extends
    GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Int32Value)
        Int32ValueOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    RuntimeVersion.validateProtobufGencodeVersion(
      RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      Int32Value.class.getName());
  }
  // Use Int32Value.newBuilder() to construct.
  private Int32Value(GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Int32Value() {
  }

  public static final Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.WrappersProto.internal_static_google_protobuf_Int32Value_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.WrappersProto.internal_static_google_protobuf_Int32Value_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Int32Value.class, com.google.protobuf.Int32Value.Builder.class);
  }

  public static final int VALUE_FIELD_NUMBER = 1;
  private int value_ = 0;
  /**
   * <pre>
   * The int32 value.
   * </pre>
   *
   * <code>int32 value = 1;</code>
   * @return The value.
   */
  @Override
  public int getValue() {
    return value_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (value_ != 0) {
      output.writeInt32(1, value_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (value_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, value_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Int32Value)) {
      return super.equals(obj);
    }
    com.google.protobuf.Int32Value other = (com.google.protobuf.Int32Value) obj;

    if (getValue()
        != other.getValue()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Int32Value parseFrom(
      java.nio.ByteBuffer data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      java.nio.ByteBuffer data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      ByteString data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      ByteString data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Int32Value parseFrom(byte[] data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      byte[] data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Int32Value parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Int32Value parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Int32Value parseDelimitedFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      CodedInputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Int32Value parseFrom(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Int32Value prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Wrapper message for `int32`.
   *
   * The JSON representation for `Int32Value` is JSON number.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Int32Value}
   */
  public static final class Builder extends
      GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Int32Value)
      com.google.protobuf.Int32ValueOrBuilder {
    public static final Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.WrappersProto.internal_static_google_protobuf_Int32Value_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.WrappersProto.internal_static_google_protobuf_Int32Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Int32Value.class, com.google.protobuf.Int32Value.Builder.class);
    }

    // Construct using com.google.protobuf.Int32Value.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      value_ = 0;
      return this;
    }

    @Override
    public Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.WrappersProto.internal_static_google_protobuf_Int32Value_descriptor;
    }

    @Override
    public com.google.protobuf.Int32Value getDefaultInstanceForType() {
      return com.google.protobuf.Int32Value.getDefaultInstance();
    }

    @Override
    public com.google.protobuf.Int32Value build() {
      com.google.protobuf.Int32Value result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.google.protobuf.Int32Value buildPartial() {
      com.google.protobuf.Int32Value result = new com.google.protobuf.Int32Value(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.protobuf.Int32Value result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.value_ = value_;
      }
    }

    @Override
    public Builder mergeFrom(Message other) {
      if (other instanceof com.google.protobuf.Int32Value) {
        return mergeFrom((com.google.protobuf.Int32Value)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Int32Value other) {
      if (other == com.google.protobuf.Int32Value.getDefaultInstance()) return this;
      if (other.getValue() != 0) {
        setValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              value_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int value_ ;
    /**
     * <pre>
     * The int32 value.
     * </pre>
     *
     * <code>int32 value = 1;</code>
     * @return The value.
     */
    @Override
    public int getValue() {
      return value_;
    }
    /**
     * <pre>
     * The int32 value.
     * </pre>
     *
     * <code>int32 value = 1;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(int value) {

      value_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The int32 value.
     * </pre>
     *
     * <code>int32 value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      value_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Int32Value)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Int32Value)
  private static final com.google.protobuf.Int32Value DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Int32Value();
  }

  public static com.google.protobuf.Int32Value getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  public static com.google.protobuf.Int32Value of(int value) {
    return newBuilder().setValue(value).build();
  }

  private static final com.google.protobuf.Parser<Int32Value>
      PARSER = new AbstractParser<Int32Value>() {
    @Override
    public Int32Value parsePartialFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Int32Value> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Int32Value> getParserForType() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Int32Value getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

