// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/source_context.proto
// Protobuf Java Version: 4.29.0

package com.google.protobuf;

/**
 * <pre>
 * `SourceContext` represents information about the source of a
 * protobuf element, like the file in which it is defined.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.SourceContext}
 */
public final class SourceContext extends
    GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.SourceContext)
        SourceContextOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    RuntimeVersion.validateProtobufGencodeVersion(
      RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      SourceContext.class.getName());
  }
  // Use SourceContext.newBuilder() to construct.
  private SourceContext(GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SourceContext() {
    fileName_ = "";
  }

  public static final Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.SourceContextProto.internal_static_google_protobuf_SourceContext_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.SourceContextProto.internal_static_google_protobuf_SourceContext_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.SourceContext.class, com.google.protobuf.SourceContext.Builder.class);
  }

  public static final int FILE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object fileName_ = "";
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  @Override
  public String getFileName() {
    Object ref = fileName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      ByteString bs =
          (ByteString) ref;
      String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The path-qualified name of the .proto file that contained the associated
   * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
   * </pre>
   *
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  @Override
  public ByteString
      getFileNameBytes() {
    Object ref = fileName_;
    if (ref instanceof String) {
      ByteString b =
          ByteString.copyFromUtf8(
              (String) ref);
      fileName_ = b;
      return b;
    } else {
      return (ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!GeneratedMessage.isStringEmpty(fileName_)) {
      GeneratedMessage.writeString(output, 1, fileName_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!GeneratedMessage.isStringEmpty(fileName_)) {
      size += GeneratedMessage.computeStringSize(1, fileName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.SourceContext)) {
      return super.equals(obj);
    }
    com.google.protobuf.SourceContext other = (com.google.protobuf.SourceContext) obj;

    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.SourceContext parseFrom(
      java.nio.ByteBuffer data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      java.nio.ByteBuffer data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      ByteString data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      ByteString data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(byte[] data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      byte[] data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.SourceContext parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.SourceContext parseDelimitedFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      CodedInputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.SourceContext parseFrom(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.SourceContext prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * `SourceContext` represents information about the source of a
   * protobuf element, like the file in which it is defined.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.SourceContext}
   */
  public static final class Builder extends
      GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.SourceContext)
      SourceContextOrBuilder {
    public static final Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.SourceContextProto.internal_static_google_protobuf_SourceContext_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.SourceContextProto.internal_static_google_protobuf_SourceContext_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.SourceContext.class, com.google.protobuf.SourceContext.Builder.class);
    }

    // Construct using com.google.protobuf.SourceContext.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fileName_ = "";
      return this;
    }

    @Override
    public Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.SourceContextProto.internal_static_google_protobuf_SourceContext_descriptor;
    }

    @Override
    public com.google.protobuf.SourceContext getDefaultInstanceForType() {
      return com.google.protobuf.SourceContext.getDefaultInstance();
    }

    @Override
    public com.google.protobuf.SourceContext build() {
      com.google.protobuf.SourceContext result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.google.protobuf.SourceContext buildPartial() {
      com.google.protobuf.SourceContext result = new com.google.protobuf.SourceContext(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.protobuf.SourceContext result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fileName_ = fileName_;
      }
    }

    @Override
    public Builder mergeFrom(Message other) {
      if (other instanceof com.google.protobuf.SourceContext) {
        return mergeFrom((com.google.protobuf.SourceContext)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.SourceContext other) {
      if (other == com.google.protobuf.SourceContext.getDefaultInstance()) return this;
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              fileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object fileName_ = "";
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @return The fileName.
     */
    public String getFileName() {
      Object ref = fileName_;
      if (!(ref instanceof String)) {
        ByteString bs =
            (ByteString) ref;
        String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @return The bytes for fileName.
     */
    public ByteString
        getFileNameBytes() {
      Object ref = fileName_;
      if (ref instanceof String) {
        ByteString b =
            ByteString.copyFromUtf8(
                (String) ref);
        fileName_ = b;
        return b;
      } else {
        return (ByteString) ref;
      }
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      fileName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The path-qualified name of the .proto file that contained the associated
     * protobuf element.  For example: `"google/protobuf/source_context.proto"`.
     * </pre>
     *
     * <code>string file_name = 1;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fileName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.SourceContext)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.SourceContext)
  private static final com.google.protobuf.SourceContext DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.SourceContext();
  }

  public static com.google.protobuf.SourceContext getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final Parser<SourceContext>
      PARSER = new AbstractParser<SourceContext>() {
    @Override
    public SourceContext parsePartialFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static Parser<SourceContext> parser() {
    return PARSER;
  }

  @Override
  public Parser<SourceContext> getParserForType() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.SourceContext getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

