// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/source_context.proto
// Protobuf Java Version: 4.29.0

package com.google.protobuf;

public final class SourceContextProto {
  private SourceContextProto() {}
  static {
    RuntimeVersion.validateProtobufGencodeVersion(
      RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      SourceContextProto.class.getName());
  }
  public static void registerAllExtensions(
      ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      ExtensionRegistry registry) {
    registerAllExtensions(
        (ExtensionRegistryLite) registry);
  }
  static final Descriptors.Descriptor
    internal_static_google_protobuf_SourceContext_descriptor;
  static final 
    GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_SourceContext_fieldAccessorTable;

  public static Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n$google/protobuf/source_context.proto\022\017" +
      "google.protobuf\"\"\n\rSourceContext\022\021\n\tfile" +
      "_name\030\001 \001(\tB\212\001\n\023com.google.protobufB\022Sou" +
      "rceContextProtoP\001Z6google.golang.org/pro" +
      "tobuf/types/known/sourcecontextpb\242\002\003GPB\252" +
      "\002\036Google.Protobuf.WellKnownTypesb\006proto3"
    };
    descriptor = Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_SourceContext_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_SourceContext_fieldAccessorTable = new
      GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_SourceContext_descriptor,
        new String[] { "FileName", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
