// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.29.0

package com.google.protobuf;

public interface StructOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Struct)
    MessageOrBuilder {

  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  int getFieldsCount();
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  boolean containsFields(
      String key);
  /**
   * Use {@link #getFieldsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, com.google.protobuf.Value>
  getFields();
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  java.util.Map<String, com.google.protobuf.Value>
  getFieldsMap();
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  /* nullable */
com.google.protobuf.Value getFieldsOrDefault(
      String key,
      /* nullable */
com.google.protobuf.Value defaultValue);
  /**
   * <pre>
   * Unordered map of dynamically typed values.
   * </pre>
   *
   * <code>map&lt;string, .google.protobuf.Value&gt; fields = 1;</code>
   */
  com.google.protobuf.Value getFieldsOrThrow(
      String key);
}
