// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/struct.proto
// Protobuf Java Version: 4.29.0

package com.google.protobuf;

/**
 * <pre>
 * `Value` represents a dynamically typed value which can be either
 * null, a number, a string, a boolean, a recursive struct value, or a
 * list of values. A producer of value is expected to set one of these
 * variants. Absence of any variant indicates an error.
 *
 * The JSON representation for `Value` is JSON value.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Value}
 */
public final class Value extends
    GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Value)
        ValueOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    RuntimeVersion.validateProtobufGencodeVersion(
      RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      Value.class.getName());
  }
  // Use Value.newBuilder() to construct.
  private Value(GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Value() {
  }

  public static final Descriptors.Descriptor
      getDescriptor() {
    return StructProto.internal_static_google_protobuf_Value_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return StructProto.internal_static_google_protobuf_Value_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.Value.class, com.google.protobuf.Value.Builder.class);
  }

  private int kindCase_ = 0;
  @SuppressWarnings("serial")
  private Object kind_;
  public enum KindCase
      implements Internal.EnumLite,
          InternalOneOfEnum {
    NULL_VALUE(1),
    NUMBER_VALUE(2),
    STRING_VALUE(3),
    BOOL_VALUE(4),
    STRUCT_VALUE(5),
    LIST_VALUE(6),
    KIND_NOT_SET(0);
    private final int value;
    private KindCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static KindCase valueOf(int value) {
      return forNumber(value);
    }

    public static KindCase forNumber(int value) {
      switch (value) {
        case 1: return NULL_VALUE;
        case 2: return NUMBER_VALUE;
        case 3: return STRING_VALUE;
        case 4: return BOOL_VALUE;
        case 5: return STRUCT_VALUE;
        case 6: return LIST_VALUE;
        case 0: return KIND_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public KindCase
  getKindCase() {
    return KindCase.forNumber(
        kindCase_);
  }

  public static final int NULL_VALUE_FIELD_NUMBER = 1;
  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 1;</code>
   * @return Whether the nullValue field is set.
   */
  public boolean hasNullValue() {
    return kindCase_ == 1;
  }
  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 1;</code>
   * @return The enum numeric value on the wire for nullValue.
   */
  public int getNullValueValue() {
    if (kindCase_ == 1) {
      return (Integer) kind_;
    }
    return 0;
  }
  /**
   * <pre>
   * Represents a null value.
   * </pre>
   *
   * <code>.google.protobuf.NullValue null_value = 1;</code>
   * @return The nullValue.
   */
  public NullValue getNullValue() {
    if (kindCase_ == 1) {
      NullValue result = NullValue.forNumber(
          (Integer) kind_);
      return result == null ? NullValue.UNRECOGNIZED : result;
    }
    return NullValue.NULL_VALUE;
  }

  public static final int NUMBER_VALUE_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Represents a double value.
   * </pre>
   *
   * <code>double number_value = 2;</code>
   * @return Whether the numberValue field is set.
   */
  @Override
  public boolean hasNumberValue() {
    return kindCase_ == 2;
  }
  /**
   * <pre>
   * Represents a double value.
   * </pre>
   *
   * <code>double number_value = 2;</code>
   * @return The numberValue.
   */
  @Override
  public double getNumberValue() {
    if (kindCase_ == 2) {
      return (Double) kind_;
    }
    return 0D;
  }

  public static final int STRING_VALUE_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>string string_value = 3;</code>
   * @return Whether the stringValue field is set.
   */
  public boolean hasStringValue() {
    return kindCase_ == 3;
  }
  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>string string_value = 3;</code>
   * @return The stringValue.
   */
  public String getStringValue() {
    Object ref = "";
    if (kindCase_ == 3) {
      ref = kind_;
    }
    if (ref instanceof String) {
      return (String) ref;
    } else {
      ByteString bs =
          (ByteString) ref;
      String s = bs.toStringUtf8();
      if (kindCase_ == 3) {
        kind_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Represents a string value.
   * </pre>
   *
   * <code>string string_value = 3;</code>
   * @return The bytes for stringValue.
   */
  public ByteString
      getStringValueBytes() {
    Object ref = "";
    if (kindCase_ == 3) {
      ref = kind_;
    }
    if (ref instanceof String) {
      ByteString b =
          ByteString.copyFromUtf8(
              (String) ref);
      if (kindCase_ == 3) {
        kind_ = b;
      }
      return b;
    } else {
      return (ByteString) ref;
    }
  }

  public static final int BOOL_VALUE_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Represents a boolean value.
   * </pre>
   *
   * <code>bool bool_value = 4;</code>
   * @return Whether the boolValue field is set.
   */
  @Override
  public boolean hasBoolValue() {
    return kindCase_ == 4;
  }
  /**
   * <pre>
   * Represents a boolean value.
   * </pre>
   *
   * <code>bool bool_value = 4;</code>
   * @return The boolValue.
   */
  @Override
  public boolean getBoolValue() {
    if (kindCase_ == 4) {
      return (Boolean) kind_;
    }
    return false;
  }

  public static final int STRUCT_VALUE_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>.google.protobuf.Struct struct_value = 5;</code>
   * @return Whether the structValue field is set.
   */
  @Override
  public boolean hasStructValue() {
    return kindCase_ == 5;
  }
  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>.google.protobuf.Struct struct_value = 5;</code>
   * @return The structValue.
   */
  @Override
  public Struct getStructValue() {
    if (kindCase_ == 5) {
       return (Struct) kind_;
    }
    return Struct.getDefaultInstance();
  }
  /**
   * <pre>
   * Represents a structured value.
   * </pre>
   *
   * <code>.google.protobuf.Struct struct_value = 5;</code>
   */
  @Override
  public StructOrBuilder getStructValueOrBuilder() {
    if (kindCase_ == 5) {
       return (Struct) kind_;
    }
    return Struct.getDefaultInstance();
  }

  public static final int LIST_VALUE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>.google.protobuf.ListValue list_value = 6;</code>
   * @return Whether the listValue field is set.
   */
  @Override
  public boolean hasListValue() {
    return kindCase_ == 6;
  }
  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>.google.protobuf.ListValue list_value = 6;</code>
   * @return The listValue.
   */
  @Override
  public ListValue getListValue() {
    if (kindCase_ == 6) {
       return (ListValue) kind_;
    }
    return ListValue.getDefaultInstance();
  }
  /**
   * <pre>
   * Represents a repeated `Value`.
   * </pre>
   *
   * <code>.google.protobuf.ListValue list_value = 6;</code>
   */
  @Override
  public ListValueOrBuilder getListValueOrBuilder() {
    if (kindCase_ == 6) {
       return (ListValue) kind_;
    }
    return ListValue.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(CodedOutputStream output)
                      throws java.io.IOException {
    if (kindCase_ == 1) {
      output.writeEnum(1, ((Integer) kind_));
    }
    if (kindCase_ == 2) {
      output.writeDouble(
          2, (double)((Double) kind_));
    }
    if (kindCase_ == 3) {
      GeneratedMessage.writeString(output, 3, kind_);
    }
    if (kindCase_ == 4) {
      output.writeBool(
          4, (boolean)((Boolean) kind_));
    }
    if (kindCase_ == 5) {
      output.writeMessage(5, (Struct) kind_);
    }
    if (kindCase_ == 6) {
      output.writeMessage(6, (ListValue) kind_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (kindCase_ == 1) {
      size += CodedOutputStream
        .computeEnumSize(1, ((Integer) kind_));
    }
    if (kindCase_ == 2) {
      size += CodedOutputStream
        .computeDoubleSize(
            2, (double)((Double) kind_));
    }
    if (kindCase_ == 3) {
      size += GeneratedMessage.computeStringSize(3, kind_);
    }
    if (kindCase_ == 4) {
      size += CodedOutputStream
        .computeBoolSize(
            4, (boolean)((Boolean) kind_));
    }
    if (kindCase_ == 5) {
      size += CodedOutputStream
        .computeMessageSize(5, (Struct) kind_);
    }
    if (kindCase_ == 6) {
      size += CodedOutputStream
        .computeMessageSize(6, (ListValue) kind_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.protobuf.Value)) {
      return super.equals(obj);
    }
    com.google.protobuf.Value other = (com.google.protobuf.Value) obj;

    if (!getKindCase().equals(other.getKindCase())) return false;
    switch (kindCase_) {
      case 1:
        if (getNullValueValue()
            != other.getNullValueValue()) return false;
        break;
      case 2:
        if (Double.doubleToLongBits(getNumberValue())
            != Double.doubleToLongBits(
                other.getNumberValue())) return false;
        break;
      case 3:
        if (!getStringValue()
            .equals(other.getStringValue())) return false;
        break;
      case 4:
        if (getBoolValue()
            != other.getBoolValue()) return false;
        break;
      case 5:
        if (!getStructValue()
            .equals(other.getStructValue())) return false;
        break;
      case 6:
        if (!getListValue()
            .equals(other.getListValue())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (kindCase_) {
      case 1:
        hash = (37 * hash) + NULL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getNullValueValue();
        break;
      case 2:
        hash = (37 * hash) + NUMBER_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + Internal.hashLong(
            Double.doubleToLongBits(getNumberValue()));
        break;
      case 3:
        hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStringValue().hashCode();
        break;
      case 4:
        hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + Internal.hashBoolean(
            getBoolValue());
        break;
      case 5:
        hash = (37 * hash) + STRUCT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getStructValue().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LIST_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getListValue().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.protobuf.Value parseFrom(
      java.nio.ByteBuffer data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Value parseFrom(
      java.nio.ByteBuffer data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(
      ByteString data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Value parseFrom(
      ByteString data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(byte[] data)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.Value parseFrom(
      byte[] data,
      ExtensionRegistryLite extensionRegistry)
      throws InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Value parseFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.protobuf.Value parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.protobuf.Value parseDelimitedFrom(
      java.io.InputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.protobuf.Value parseFrom(
      CodedInputStream input)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.protobuf.Value parseFrom(
      CodedInputStream input,
      ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.protobuf.Value prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * `Value` represents a dynamically typed value which can be either
   * null, a number, a string, a boolean, a recursive struct value, or a
   * list of values. A producer of value is expected to set one of these
   * variants. Absence of any variant indicates an error.
   *
   * The JSON representation for `Value` is JSON value.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Value}
   */
  public static final class Builder extends
      GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Value)
      ValueOrBuilder {
    public static final Descriptors.Descriptor
        getDescriptor() {
      return StructProto.internal_static_google_protobuf_Value_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return StructProto.internal_static_google_protobuf_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.Value.class, com.google.protobuf.Value.Builder.class);
    }

    // Construct using com.google.protobuf.Value.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (structValueBuilder_ != null) {
        structValueBuilder_.clear();
      }
      if (listValueBuilder_ != null) {
        listValueBuilder_.clear();
      }
      kindCase_ = 0;
      kind_ = null;
      return this;
    }

    @Override
    public Descriptors.Descriptor
        getDescriptorForType() {
      return StructProto.internal_static_google_protobuf_Value_descriptor;
    }

    @Override
    public com.google.protobuf.Value getDefaultInstanceForType() {
      return com.google.protobuf.Value.getDefaultInstance();
    }

    @Override
    public com.google.protobuf.Value build() {
      com.google.protobuf.Value result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.google.protobuf.Value buildPartial() {
      com.google.protobuf.Value result = new com.google.protobuf.Value(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.protobuf.Value result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(com.google.protobuf.Value result) {
      result.kindCase_ = kindCase_;
      result.kind_ = this.kind_;
      if (kindCase_ == 5 &&
          structValueBuilder_ != null) {
        result.kind_ = structValueBuilder_.build();
      }
      if (kindCase_ == 6 &&
          listValueBuilder_ != null) {
        result.kind_ = listValueBuilder_.build();
      }
    }

    @Override
    public Builder mergeFrom(Message other) {
      if (other instanceof com.google.protobuf.Value) {
        return mergeFrom((com.google.protobuf.Value)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.Value other) {
      if (other == com.google.protobuf.Value.getDefaultInstance()) return this;
      switch (other.getKindCase()) {
        case NULL_VALUE: {
          setNullValueValue(other.getNullValueValue());
          break;
        }
        case NUMBER_VALUE: {
          setNumberValue(other.getNumberValue());
          break;
        }
        case STRING_VALUE: {
          kindCase_ = 3;
          kind_ = other.kind_;
          onChanged();
          break;
        }
        case BOOL_VALUE: {
          setBoolValue(other.getBoolValue());
          break;
        }
        case STRUCT_VALUE: {
          mergeStructValue(other.getStructValue());
          break;
        }
        case LIST_VALUE: {
          mergeListValue(other.getListValue());
          break;
        }
        case KIND_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
              kindCase_ = 1;
              kind_ = rawValue;
              break;
            } // case 8
            case 17: {
              kind_ = input.readDouble();
              kindCase_ = 2;
              break;
            } // case 17
            case 26: {
              String s = input.readStringRequireUtf8();
              kindCase_ = 3;
              kind_ = s;
              break;
            } // case 26
            case 32: {
              kind_ = input.readBool();
              kindCase_ = 4;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getStructValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getListValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              kindCase_ = 6;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int kindCase_ = 0;
    private Object kind_;
    public KindCase
        getKindCase() {
      return KindCase.forNumber(
          kindCase_);
    }

    public Builder clearKind() {
      kindCase_ = 0;
      kind_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return Whether the nullValue field is set.
     */
    @Override
    public boolean hasNullValue() {
      return kindCase_ == 1;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return The enum numeric value on the wire for nullValue.
     */
    @Override
    public int getNullValueValue() {
      if (kindCase_ == 1) {
        return ((Integer) kind_).intValue();
      }
      return 0;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @param value The enum numeric value on the wire for nullValue to set.
     * @return This builder for chaining.
     */
    public Builder setNullValueValue(int value) {
      kindCase_ = 1;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return The nullValue.
     */
    @Override
    public NullValue getNullValue() {
      if (kindCase_ == 1) {
        NullValue result = NullValue.forNumber(
            (Integer) kind_);
        return result == null ? NullValue.UNRECOGNIZED : result;
      }
      return NullValue.NULL_VALUE;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @param value The nullValue to set.
     * @return This builder for chaining.
     */
    public Builder setNullValue(NullValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      kindCase_ = 1;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represents a null value.
     * </pre>
     *
     * <code>.google.protobuf.NullValue null_value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNullValue() {
      if (kindCase_ == 1) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @return Whether the numberValue field is set.
     */
    public boolean hasNumberValue() {
      return kindCase_ == 2;
    }
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @return The numberValue.
     */
    public double getNumberValue() {
      if (kindCase_ == 2) {
        return (Double) kind_;
      }
      return 0D;
    }
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @param value The numberValue to set.
     * @return This builder for chaining.
     */
    public Builder setNumberValue(double value) {

      kindCase_ = 2;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represents a double value.
     * </pre>
     *
     * <code>double number_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberValue() {
      if (kindCase_ == 2) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return Whether the stringValue field is set.
     */
    @Override
    public boolean hasStringValue() {
      return kindCase_ == 3;
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return The stringValue.
     */
    @Override
    public String getStringValue() {
      Object ref = "";
      if (kindCase_ == 3) {
        ref = kind_;
      }
      if (!(ref instanceof String)) {
        ByteString bs =
            (ByteString) ref;
        String s = bs.toStringUtf8();
        if (kindCase_ == 3) {
          kind_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return The bytes for stringValue.
     */
    @Override
    public ByteString
        getStringValueBytes() {
      Object ref = "";
      if (kindCase_ == 3) {
        ref = kind_;
      }
      if (ref instanceof String) {
        ByteString b =
            ByteString.copyFromUtf8(
                (String) ref);
        if (kindCase_ == 3) {
          kind_ = b;
        }
        return b;
      } else {
        return (ByteString) ref;
      }
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @param value The stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValue(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStringValue() {
      if (kindCase_ == 3) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Represents a string value.
     * </pre>
     *
     * <code>string string_value = 3;</code>
     * @param value The bytes for stringValue to set.
     * @return This builder for chaining.
     */
    public Builder setStringValueBytes(
        ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kindCase_ = 3;
      kind_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @return Whether the boolValue field is set.
     */
    public boolean hasBoolValue() {
      return kindCase_ == 4;
    }
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @return The boolValue.
     */
    public boolean getBoolValue() {
      if (kindCase_ == 4) {
        return (Boolean) kind_;
      }
      return false;
    }
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @param value The boolValue to set.
     * @return This builder for chaining.
     */
    public Builder setBoolValue(boolean value) {

      kindCase_ = 4;
      kind_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Represents a boolean value.
     * </pre>
     *
     * <code>bool bool_value = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBoolValue() {
      if (kindCase_ == 4) {
        kindCase_ = 0;
        kind_ = null;
        onChanged();
      }
      return this;
    }

    private SingleFieldBuilder<
        Struct, Struct.Builder, StructOrBuilder> structValueBuilder_;
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     * @return Whether the structValue field is set.
     */
    @Override
    public boolean hasStructValue() {
      return kindCase_ == 5;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     * @return The structValue.
     */
    @Override
    public Struct getStructValue() {
      if (structValueBuilder_ == null) {
        if (kindCase_ == 5) {
          return (Struct) kind_;
        }
        return Struct.getDefaultInstance();
      } else {
        if (kindCase_ == 5) {
          return structValueBuilder_.getMessage();
        }
        return Struct.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    public Builder setStructValue(Struct value) {
      if (structValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        structValueBuilder_.setMessage(value);
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    public Builder setStructValue(
        Struct.Builder builderForValue) {
      if (structValueBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        structValueBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    public Builder mergeStructValue(Struct value) {
      if (structValueBuilder_ == null) {
        if (kindCase_ == 5 &&
            kind_ != Struct.getDefaultInstance()) {
          kind_ = Struct.newBuilder((Struct) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 5) {
          structValueBuilder_.mergeFrom(value);
        } else {
          structValueBuilder_.setMessage(value);
        }
      }
      kindCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    public Builder clearStructValue() {
      if (structValueBuilder_ == null) {
        if (kindCase_ == 5) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 5) {
          kindCase_ = 0;
          kind_ = null;
        }
        structValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    public Struct.Builder getStructValueBuilder() {
      return getStructValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    @Override
    public StructOrBuilder getStructValueOrBuilder() {
      if ((kindCase_ == 5) && (structValueBuilder_ != null)) {
        return structValueBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 5) {
          return (Struct) kind_;
        }
        return Struct.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Represents a structured value.
     * </pre>
     *
     * <code>.google.protobuf.Struct struct_value = 5;</code>
     */
    private SingleFieldBuilder<
        Struct, Struct.Builder, StructOrBuilder>
        getStructValueFieldBuilder() {
      if (structValueBuilder_ == null) {
        if (!(kindCase_ == 5)) {
          kind_ = Struct.getDefaultInstance();
        }
        structValueBuilder_ = new SingleFieldBuilder<
            Struct, Struct.Builder, StructOrBuilder>(
                (Struct) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 5;
      onChanged();
      return structValueBuilder_;
    }

    private SingleFieldBuilder<
        ListValue, ListValue.Builder, ListValueOrBuilder> listValueBuilder_;
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     * @return Whether the listValue field is set.
     */
    @Override
    public boolean hasListValue() {
      return kindCase_ == 6;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     * @return The listValue.
     */
    @Override
    public ListValue getListValue() {
      if (listValueBuilder_ == null) {
        if (kindCase_ == 6) {
          return (ListValue) kind_;
        }
        return ListValue.getDefaultInstance();
      } else {
        if (kindCase_ == 6) {
          return listValueBuilder_.getMessage();
        }
        return ListValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    public Builder setListValue(ListValue value) {
      if (listValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        kind_ = value;
        onChanged();
      } else {
        listValueBuilder_.setMessage(value);
      }
      kindCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    public Builder setListValue(
        ListValue.Builder builderForValue) {
      if (listValueBuilder_ == null) {
        kind_ = builderForValue.build();
        onChanged();
      } else {
        listValueBuilder_.setMessage(builderForValue.build());
      }
      kindCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    public Builder mergeListValue(ListValue value) {
      if (listValueBuilder_ == null) {
        if (kindCase_ == 6 &&
            kind_ != ListValue.getDefaultInstance()) {
          kind_ = ListValue.newBuilder((ListValue) kind_)
              .mergeFrom(value).buildPartial();
        } else {
          kind_ = value;
        }
        onChanged();
      } else {
        if (kindCase_ == 6) {
          listValueBuilder_.mergeFrom(value);
        } else {
          listValueBuilder_.setMessage(value);
        }
      }
      kindCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    public Builder clearListValue() {
      if (listValueBuilder_ == null) {
        if (kindCase_ == 6) {
          kindCase_ = 0;
          kind_ = null;
          onChanged();
        }
      } else {
        if (kindCase_ == 6) {
          kindCase_ = 0;
          kind_ = null;
        }
        listValueBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    public ListValue.Builder getListValueBuilder() {
      return getListValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    @Override
    public ListValueOrBuilder getListValueOrBuilder() {
      if ((kindCase_ == 6) && (listValueBuilder_ != null)) {
        return listValueBuilder_.getMessageOrBuilder();
      } else {
        if (kindCase_ == 6) {
          return (ListValue) kind_;
        }
        return ListValue.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Represents a repeated `Value`.
     * </pre>
     *
     * <code>.google.protobuf.ListValue list_value = 6;</code>
     */
    private SingleFieldBuilder<
        ListValue, ListValue.Builder, ListValueOrBuilder>
        getListValueFieldBuilder() {
      if (listValueBuilder_ == null) {
        if (!(kindCase_ == 6)) {
          kind_ = ListValue.getDefaultInstance();
        }
        listValueBuilder_ = new SingleFieldBuilder<
            ListValue, ListValue.Builder, ListValueOrBuilder>(
                (ListValue) kind_,
                getParentForChildren(),
                isClean());
        kind_ = null;
      }
      kindCase_ = 6;
      onChanged();
      return listValueBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.Value)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Value)
  private static final com.google.protobuf.Value DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.protobuf.Value();
  }

  public static com.google.protobuf.Value getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final Parser<Value>
      PARSER = new AbstractParser<Value>() {
    @Override
    public Value parsePartialFrom(
        CodedInputStream input,
        ExtensionRegistryLite extensionRegistry)
        throws InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static Parser<Value> parser() {
    return PARSER;
  }

  @Override
  public Parser<Value> getParserForType() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Value getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

